ALTER TABLE gps_data
  ALTER COLUMN latitude  TYPE DECIMAL(11,8),
  ALTER COLUMN longitude TYPE DECIMAL(11,8),
  ALTER COLUMN altitude  TYPE DECIMAL(10,4),
  ALTER COLUMN speed     TYPE DECIMAL(8,4);

ALTER TABLE waste_collection
 ALTER COLUMN amount TYPE SERIAL NOT NULL; 
